/**
 * VANTA AI — demo clip catalog.
 *
 * Drop compressed 1080p (or 720p) web-friendly MP4s into /public/videos/
 * and matching poster .webp files into /public/posters/ (same basename).
 *
 * Use compressed web versions here. Keep raw 4K masters outside the frontend.
 *
 * Until real files exist, the VideoMedia component shows a premium gradient
 * fallback automatically — no broken players, no black boxes.
 *
 * SAFETY: these are placeholders labeled as "sample cinematic demo clips"
 * across the UI. Do NOT label them as "Generated by VANTA" until confirmed.
 * Verify license before using any third-party demo clip in production.
 */

import type { Tone } from "@/components/vanta/VideoMedia";

export type DemoClip = {
  id: string;
  title: string;
  category: string;
  duration: string;
  aspect: "16:9" | "9:16" | "1:1";
  video: string;
  poster: string;
  prompt: string;
  tone: Tone; // fallback gradient tone
};

export const demoClips: DemoClip[] = [
  {
    id: "futuristic-city",
    title: "Futuristic City",
    category: "Sci-fi",
    duration: "10s",
    aspect: "16:9",
    video: "/videos/futuristic-city.mp4",
    poster: "/posters/futuristic-city.webp",
    prompt: "Aerial dolly through a neon megacity at dusk.",
    tone: "violet",
  },
  {
    id: "luxury-product-ad",
    title: "Luxury Product Ad",
    category: "Product",
    duration: "8s",
    aspect: "16:9",
    video: "/videos/luxury-product-ad.mp4",
    poster: "/posters/luxury-product-ad.webp",
    prompt: "Black hoodie rotating in a dark studio, soft rim light.",
    tone: "noir",
  },
  {
    id: "horror-story",
    title: "Horror Story Scene",
    category: "Horror",
    duration: "10s",
    aspect: "16:9",
    video: "/videos/horror-story.mp4",
    poster: "/posters/horror-story.webp",
    prompt: "Slow push into an abandoned hallway with a flickering bulb.",
    tone: "ember",
  },
  {
    id: "documentary-broll",
    title: "Documentary B-roll",
    category: "Doc",
    duration: "6s",
    aspect: "16:9",
    video: "/videos/documentary-broll.mp4",
    poster: "/posters/documentary-broll.webp",
    prompt: "Hands assembling a vintage camera in warm window light.",
    tone: "amber",
  },
  {
    id: "anime-rooftop",
    title: "Anime Rooftop",
    category: "Anime",
    duration: "8s",
    aspect: "16:9",
    video: "/videos/anime-rooftop.mp4",
    poster: "/posters/anime-rooftop.webp",
    prompt: "Rain-soaked rooftop confrontation under neon signs.",
    tone: "teal",
  },
  {
    id: "tech-explainer",
    title: "Tech Explainer",
    category: "Tech",
    duration: "10s",
    aspect: "16:9",
    video: "/videos/tech-explainer.mp4",
    poster: "/posters/tech-explainer.webp",
    prompt: "Floating dashboard interface with holographic callouts.",
    tone: "ice",
  },
  {
    id: "business-motivation",
    title: "Business Motivation",
    category: "Business",
    duration: "10s",
    aspect: "16:9",
    video: "/videos/business-motivation.mp4",
    poster: "/posters/business-motivation.webp",
    prompt: "Founder walking through a glass office before sunrise.",
    tone: "amber",
  },
];

export const heroClip = {
  video: "/videos/hero-vanta-reel.mp4",
  poster: "/posters/hero-vanta-reel.webp",
  title: "VANTA AI hero reel",
  tone: "violet" as Tone,
};

export const galleryCategories = [
  "All",
  "Sci-fi",
  "Product",
  "Horror",
  "Doc",
  "Anime",
  "Tech",
  "Business",
];
